global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metric_relabel_configs:
      - source_labels: [namespace]
        regex: "ecommerce"
        action: keep

  - job_name: 'ecommerce-service'
    static_configs:
      - targets: ['app:4000']
    metrics_path: '/metrics'
    scrape_interval: 5s